export const DEFAULT_DATA = {};

export enum SectionType {
  ADS = 'ADS',
  BANNER = 'BANNER',
  SERVICE = 'SERVICE',
  FEATURED_VIDEO = 'FEATURED_VIDEO',
  FEATURED_AUDIO = 'FEATURED_AUDIO',
  NEWEST_VIDEO = 'NEWEST_VIDEO',
  NEWEST_AUDIO = 'NEWEST_AUDIO',
}
