export const QUERY_KEYS = Object.freeze({
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",

  GET_INFO_USER: "GET_INFO_USER",
  POST_INFO_USER: "POST_INFO_USER",

  GET_ALL_LEVELS: "GET_ALL_LEVEL",
  GET_ALL_TOPICS: "GET_ALL_TOPICS",
  POST_LEVEL_TOPIC: "POST_LEVEL_TOPIC",

  GET_ALL_VIDEOS: "GET_ALL_VIDEO",
  GET_INFINITY_VIDEOS: "GET_INFINITY_VIDEOS",
  GET_VIDEOS_FEATURE: "GET_VIDEOS_FEATURE",
  GET_VIDEO_ITEM: "GET_VIDEO_ITEM",
  GET_VIDEO_TRANSCRIPT: "GET_VIDEO_TRANSCRIPT",
  GET_LIST_VIDEO_VOCAB: "GET_LIST_VIDEO_VOCAB",

  GET_EV_DICT_CLIENT: "GET_EV_DICT_CLIENT",
  GET_LIST_USER_VOCAB_FOLDER: "GET_LIST_USER_VOCAB_FOLDER",
  GET_DETAIL_USER_VOCAB_FOLDER: "GET_DETAIL_USER_VOCAB_FOLDER",

  PODCAST_LIST: "PODCAST_LIST",
  PODCAST_FEATURE_LIST: "PODCAST_FEATURE_LIST",
  ALL_TOPICS: "ALL_TOPICS",
  VIDEO_LIST: "VIDEO_LIST",
  PODCAST_DETAIL: "PODCAST_DETAIL",
  GET_POPULAR_TOPICS: "GET_POPULAR_TOPICS",
  GET_SEARCH_RESULT: "GET_SEARCH_RESULT",
  GET_SEARCH_HISTORY: "GET_SEARCH_HISTORY",
  GET_GROUP_LIST: "GET_GROUP_LIST",
  GET_SAVED_WORD_LIST: "GET_SAVED_WORD_LIST",
  GET_SAVED_WORD_DETAIL: "GET_SAVED_WORD_DETAIL",

  GET_SAVED_MEDIA_LIST: "GET_SAVED_MEDIA_LIST",
  GET_AMOUNT_QUESTION_FOR_GAME_CHOOSE_RIGHT_WORD:
    "GET_AMOUNT_QUESTION_FOR_GAME_CHOOSE",
  GAME_CHOOSE_RIGHT_WORD_CHECK_RESULT_TRUE_OR_FALSE:
    "GAME_CHOOSE_RIGHT_WORD_CHECK_RESULT_TRUE_OR_FALSE",
  GAME_CHOOSE_RIGHT_WORD_GET_CORRECT_ANSWER:
    "GAME_CHOOSE_RIGHT_WORD_GET_CORRECT_ANSWER",
  GAME_DRAG_WORD_GET_AMOUNT_QUESTION: "GAME_DRAG_WORD_GET_AMOUNT_QUESTION",
  GAME_DRAG_WORD_GET_CORRECT_ANSWER: "GAME_DRAG_WORD_GET_CORRECT_ANSWER",
  GET_AUDIO_TRANSCIPT: "GET_AUDIO_TRANSCIPT",
  GET_GAME_SHUFFLE_SENTENCE: "GET_GAME_SHUFFLE_SENTENCE",

  IS_CHECK_IN: "IS_CHECK_IN",
  GET_HOME: "GET_HOME",
  MISSION_LIST: "MISSION_LIST",
  GET_CLIENT_PLAN: "GET_CLIENT_PLAN",
  GET_DIAMOND_PACKAGE: "GET_DIAMOND_PACKAGE",
  GET_AUDIO_VOCAB: "GET_AUDIO_VOCAB",
  GET_LEFT_AMOUNT_SAVE_WORD: "GET_LEFT_AMOUNT_SAVE_WORD",
  GAME_HISTORY_ACHIEVEMENT: "GAME_HISTORY_ACHIEVEMENT",
  CHOOSE_CORRECT_MEANING_QUESTIONS_ANSWERS:
    "CHOOSE_CORRECT_MEANING_QUESTIONS_ANSWERS",
  CHOOSE_CORRECT_WORD_QUESTIONS_ANSWERS:
    "CHOOSE_CORRECT_WORD_QUESTIONS_ANSWERS",
  FILL_THE_GAP_QUESTIONS_ANSWERS: "FILL_THE_GAP_QUESTIONS_ANSWERS",

  // GAME
  GET_ACHIEVEMENTS: "GET_ACHIEVEMENTS",
  GET_FLASH_CARD: "GET_FLASH_CARD",
  GET_VIDEO_SEARCH_RESULT: "GET_VIDEO_SEARCH_RESULT",
  GET_PODCAST_SEARCH_RESULT: "GET_PODCAST_SEARCH_RESULT",
  GET_TOPIC_BY_KEY: "GET_TOPIC_BY_KEY",

  // Review Vocab
  GET_REVIEW_VOCAB: "GET_REVIEW_VOCAB",
  // RATING
  CHECK_SHOW_RATING: "CHECK_SHOW_RATING",
});
