export const QUERY_KEYS = Object.freeze({
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",

  GET_INFO_USER: "GET_INFO_USER",
  POST_INFO_USER: "POST_INFO_USER",

  GET_ALL_LEVELS: "GET_ALL_LEVEL",
  GET_ALL_TOPICS: "GET_ALL_TOPICS",
  POST_LEVEL_TOPIC: "POST_LEVEL_TOPIC",

  GET_VIDEOS_FEATURE: "GET_VIDEOS_FEATURE",
  GET_VIDEO_TRANSCRIPT: "GET_VIDEO_TRANSCRIPT",

  PODCAST_LIST: "PODCAST_LIST",
  PODCAST_FEATURE_LIST: "PODCAST_FEATURE_LIST",
  ALL_TOPICS: "ALL_TOPICS",
  VIDEO_LIST: "VIDEO_LIST",
  PODCAST_DETAIL: "PODCAST_DETAIL",
  GET_POPULAR_TOPICS: "GET_POPULAR_TOPICS",
  GET_SEARCH_RESULT: "GET_SEARCH_RESULT",
  GET_SEARCH_HISTORY: "GET_SEARCH_HISTORY",
  GET_GROUP_LIST: "GET_GROUP_LIST",
  GET_SAVED_WORD_LIST: "GET_SAVED_WORD_LIST",
  GET_SAVED_WORD_DETAIL: "GET_SAVED_WORD_DETAIL",

  GET_SAVED_MEDIA_LIST: "GET_SAVED_MEDIA_LIST",

  GET_AUDIO_TRANSCIPT: "GET_AUDIO_TRANSCIPT",

  IS_CHECK_IN: "IS_CHECK_IN",
  GET_HOME: "GET_HOME",
  MISSION_LIST: "MISSION_LIST",
  GET_CLIENT_PLAN: "GET_CLIENT_PLAN",
  GET_DIAMOND_PACKAGE: "GET_DIAMOND_PACKAGE",
  GET_LEFT_AMOUNT_SAVE_WORD: "GET_LEFT_AMOUNT_SAVE_WORD",
});
